server{ #----Server: este bloque define un servidor virtual 
#Dentro de el decimos como se portará NGINX al recibir las peticiones HTTP 
    listen 80; #Le indicamos a NGINX que escuche el puerto 80, el puerto por defecto para HTTP
    location / { #Este bloque indica lo que debe hacer NGINX cuando llega una petición a la ruta raíz
        include uwsgi_params; #--NGINX incluye parametros necesarios para comunicarse con una aplicacion 
        #usando el protocolo uWSGI
        uwsgi_pass flask:8080; #NGINX envía las solicitudes a un servidor uWSGI que está escuchado en el 
        #host flak y en el puerto 8080
    } 
}

